### ISSUE TITLE
 error message 

### ISSUE THREAD

**Issue by KyrisEcono** [quickbreach/ExchangeRelayX#1]
1.
**python exchangeRelayx.py -o -t https://mail.github.com -l 127.0.0.1**
returns the following error:

```
[*] Testing https://mail.github.com/EWS/Exchange.asmx for NTLM authentication support...
[*] SUCCESS - Server supports NTLM authentication
Traceback (most recent call last):
  File "exchangeRelayx.py", line 104, in <module>
    startServers(targetURL, outputFile, serverIP, serverPort)
  File "exchangeRelayx.py", line 72, in startServers
    s = server(c)
  File "/usr/local/lib/python2.7/dist-packages/impacket/examples/ntlmrelayx/servers/smbrelayserver.py", line 84, in __init__
    self.server.processConfigFile()
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbserver.py", line 4346, in processConfigFile
    self.__jtr_dump_path = self.__serverConfig.get("global", "jtr_dump_path")
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 663, in _interpolate
    if value and "%(" in value:
TypeError: argument of type 'bool' is not iterable
```

2.
chrome open url "Go to Portal",   

chrome returns the following error:
`Error loading subfolders :(`

**Comment by quickbreach** [comment]
Fixed in commit ca2758f47f22f2f424d379bbbd28aa9b05435dfc
